x = 10
y = 9

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)
print(x ** y)
print("===========================================")

print(abs(x - y))
print(pow(x, y))
print(round(3.14159, 2))
print(max(x, y))
print(min(x, y))
print(int(3.7))
print(float(x))
print(str(x))
print("===========================================")
print(bin(x))
print(oct(x))
print(hex(x))
print(complex(x, y))
print(divmod(x, y))
print(format(x, 'b'))
print(chr(65))
print(ord('A'))
print(bool(x))
print("===========================================")
print(len(str(x)))
print(sorted([x, y]))
print(repr(x))
print(eval('x + y'))
print(type(x))
print(id(x))
print("===========================================")
print(isinstance(x, int))
print(all([x > 0, y > 0]))
print(any([x > 0, y < 0]))
print(sum([x, y]))
print(enumerate([x, y]))
print(zip([x], [y]))